version: '3'
services: 
  yolo-web-db: 
    image: mongo:5.0.16 
    environment: 
      MONGO_INITDB_DATABSE: yolomy
    ports: 
      8000:8000
  yolo-web-client: 
    image: yolo-web-client:latest
    environment:
      PORT: 3000
      PROXY_API: https://yolo-web-backend:8080/
    ports:
      -3000:3000
  yolo-web-backend: 
    image: yolo-web-backend:latest
    environment:
      MONGODB_URI: mongodb://yolo-web-db:8000/yolomy
    ports:
      -8080:8080
    




  
