version: '3'
services: 
  yolo-web-db: 
    image: mongo:5.0.16 
    environment: 
      MONGO_INITDB_DATABSE: yolomy
    ports: 
      - 27017:27017
    networks:
    - yolo-networks 
    volumes:
    - yolo-volumes:/etc/data/backend
    
  yolo-web-client: 
    image: pwambura/yolo-web-client:v1.0.0
    environment:
      PORT: 3000
      PROXY_API: http://yolo-web-backend:5000/
    ports:
      - 3000:3000
    networks:
    - yolo-networks 
  
  yolo-web-backend: 
    image: pwambura/yolo-web-backend:v1.0.0
    environment:
      MONGODB_URI: mongodb://yolo-web-db:27017/yolomy
    ports:
      - 5000:5000
    networks:
    - yolo-networks 
    volumes:
    - yolo-volumes:/etc/data/backend

networks: 
  yolo-networks: 
    driver: bridge 

volumes:
  yolo-volumes: 





  
