version: '3'
services: 
  yolo-web-db: 
    image: mongo:5.0.16 
    environment: 
      MONGO_INITDB_DATABSE: yolomy
    ports: 
      27017:27017
  yolo-web-client: 
    image: pwambura/yolo-web-client:v1.0.0
    environment:
      PORT: 3000
      PROXY_API: http://yolo-web-backend:8080/
    ports:
      -3000:3000
  yolo-web-backend: 
    image: yolo-web-backend:latest
    environment:
      MONGODB_URI: mongodb://yolo-web-db:27017/yolomy
    ports:
      -8080:8080
    




  
